name: WINDOWS RDP - CLOUDFLARE
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 350
    steps:
      - uses: AnimMouse/setup-cloudflared@v2
      - run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "Yard4rein@." -Force)
      - run: |
          Start-Process cloudflared -ArgumentList "tunnel --url tcp://localhost:3389" -RedirectStandardError cf.log -NoNewWindow
          Start-Sleep 20
          type cf.log
          echo USERNAME: runneradmin
          echo PASSWORD: Yard4rein@.
          while ($true) { sleep 60; echo alive }
